### ISSUE TITLE
It is a file type that has not been permitted.

### ISSUE THREAD

**Issue by vnikolay** [comodojo/metaweblog#1]
Hello! i tryed to use "metaWeblog.newMediaObject" to send image its getting error "It is a file type that has not been permitted.". Tryed with $useNativeEncoder=true - same error.  I think problem in base64 coding. What it can be?

**Comment by marcogiovinazzi** [comment]
Assuming you're using wordpress, the error message seems to be related to the mime type of uploaded file.

Are you trying to upload a file not [natively permitted by wordpress](https://codex.wordpress.org/Uploading_Files)? Are you using the correct mime?

The lib seems to work fine (I just [added a test](https://github.com/comodojo/metaweblog/blob/master/tests/MetaWeblog/MetaWeblogTest.php#L105) for the `newMediaObject` method).

Also, check that you're using the latest version ([1.0.3](https://github.com/comodojo/metaweblog/releases/tag/1.0.3)) and that `$useNativeEncoder` is set to false ([rpcclient](https://github.com/comodojo/xmlrpc) does not support base64 encoding using PHP xml-rpc funcs).

**Comment by vnikolay** [comment]
Thank you, its working perfect, i check now, Its was my inattentive mistake - write the name of file without the extension. It's not wordpress, other cms plugin, that uses blogs api. Thanks for this lib! will in future lib support base64 encoding using native PHP xml-rpc funcs?

**Comment by marcogiovinazzi** [comment]
Unfortunately, not; it is not only for base64 encoding. Check this [blog post](http://jme.altervista.org/2015/01/xmlrpc-libxml-and-numeric-entities/) to know more. :)
